pipeline {
    agent any

    parameters {
            choice(
                name: 'ENV',
                choices: ['stage-01', 'prod-01','dev-01'],
                description: 'Select the environment'
            )
        }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'CI-118-implement-possibility-to-deploy-resources-depending-on-which-account-it-needs',
                    url: 'git@github.com:Code-Illuminators/Illuminators_infra.git',
                    credentialsId: 'github_ssh'
            }
        }

        stage('Assuming role') {
            steps {
                    script {
                        def account_id_map = [
                            'dev-01': '235194330448',
                            'stage-01': '123',
                            'prod-01': '321'
                        ]

                        def account_id = account_id_map[params.ENV]

                        dir('environment-setup') {
                            withAWS(roleAccount: account_id, role: "terraform-deployment-role-${params.ENV}") {
                                sh "pwd"
                                sh "cd environmet-setup"
                                sh "make plan BIRD_ENV=${params.ENV}"
                            }
                        }

                    }
                }
            }
        }
}