pipeline {
    agent any

    parameters {
            choice(
                name: 'ENV',
                choices: ['stage-01', 'prod-01','dev-01'],
                description: 'Select the environment'
            )
            choice(
                name: 'ACTION',
                choices: ['plan', 'apply', 'destroy'],
                description: 'Select the terraform action'
            )
        }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'CI-118-implement-possibility-to-deploy-resources-depending-on-which-account-it-needs',
                    url: 'git@github.com:Code-Illuminators/Illuminators_infra.git',
                    credentialsId: 'github_ssh'
            }
        }

        stage('Deployment') {
            steps {
                    script {
                        def account_id_map = [
                            'dev-01': '235194330448',
                            'stage-01': '037490753541',
                            'prod-01': '321'
                        ]

                        def account_id = account_id_map[params.ENV]

                        def jenkins_account_id = '037490753541'

                        dir('birdwatching-setup') {
                            if (account_id != jenkins_account_id) {
                            withAWS(roleAccount: account_id, role: "terraform-deployment-role-${params.ENV}") {
                                sh "make ${params.ACTION} BIRD_ENV=${params.ENV}"
                            }
                            } else {
                                sh "make ${params.ACTION} BIRD_ENV=${params.ENV}"
                            }
                            }
                        }

                    }
                }
            }
        }